In [4]:
a=np.tile(np.arange(0,40,10),(3,2))

In [2]:
import numpy as np

In [5]:
print(a)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [6]:
a=np.tile(np.arange(0,40,10),(3,1))

In [7]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [8]:
b=np.array([0,1,2])

In [9]:
b


array([0, 1, 2])

In [10]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [11]:
a=np.arange(0,40,10)

In [12]:
a.shape

(4,)

In [13]:
a=a[:,np.newaxis] #adds a new axis

In [14]:
a


array([[ 0],
       [10],
       [20],
       [30]])

In [15]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [16]:
a=np.array([[1,2,3],[4,5,6]])

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [20]:
#Reshaping

In [21]:
print(a.shape)

(2, 3)


In [22]:
b=a.ravel()

In [23]:
b

array([1, 2, 3, 4, 5, 6])

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b=b.reshape((2,3))

In [26]:
print(b)

[[1 2 3]
 [4 5 6]]


In [27]:
b[0,0]=100

In [28]:
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [29]:
#Reshape may also return a copy

In [30]:
a=np.zeros((3,2))

In [31]:
b=a.T.reshape(3*2)

In [32]:
b

array([0., 0., 0., 0., 0., 0.])

In [33]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
b[0]=50

In [35]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
z=np.array([1,2,3])

In [39]:
z=z[:,np.newaxis]

In [40]:
z

array([[[1]],

       [[2]],

       [[3]]])

In [41]:
#Dimension Shuffling

In [42]:
a=np.arange(4*3*2).reshape(4,3,2)

In [43]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [44]:
a[0,2,1]

5

In [46]:
a=np.arange(4)

In [47]:
a

array([0, 1, 2, 3])

In [50]:
a=a.resize((8,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [49]:
b=a

In [51]:
a.resize((4,))

In [52]:
a

array([0, 1, 2, 3])

In [53]:
a=np.array([[5,4,6],[2,3,2]])

In [54]:
b=np.sort(a,axis=1)

In [55]:
b


array([[4, 5, 6],
       [2, 2, 3]])

In [56]:
a.sort(axis=1)

In [57]:
a

array([[4, 5, 6],
       [2, 2, 3]])

In [58]:
a=np.array([4,3,1,2])

In [59]:
j=np.argsort(a)   

In [60]:
j  #position of indexing

array([2, 3, 1, 0], dtype=int64)

In [61]:
a[j]

array([1, 2, 3, 4])