In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4])

In [3]:
a+1

array([2, 3, 4, 5])

In [4]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [6]:
b=np.ones(4)+1

In [7]:
a-b

array([-1.,  0.,  1.,  2.])

In [8]:
a*b

array([2., 4., 6., 8.])

In [9]:
c=np.diag([1,2,3,4])

In [10]:
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [11]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [12]:
a=np.array([1,2,3,4])

In [13]:
b=np.array([5,2,2,4])


In [14]:
a==b

array([False,  True, False,  True])

In [15]:
a>b

array([False, False,  True, False])

In [16]:
a=np.array([1,2,3,4])

In [17]:
b=np.array([5,2,2,4])

In [18]:
c=np.array([1,2,3,4])

In [19]:
np.array_equal(a,b)

False

In [20]:
np.array_equal(a,c)

True

In [21]:
a=np.array([1,1,0,0],dtype=bool)

In [22]:
b=np.array([1,0,1,0],dtype=bool)

In [23]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [24]:
a=np.arange(5)

In [25]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [26]:
np.log(a)

C:\Users\DIPANKAR\AppData\Local\Temp/ipykernel_13008/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [27]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])