In [1]:
import numpy as np

In [2]:
a=np.arange(4)

In [3]:
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [4]:
x=np.array([1,2,3,4])

In [5]:
np.sum(x)

10

In [6]:
x.sum(axis=0)

10

In [7]:
x=np.array([1,1],[2,2])

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [8]:
x=np.array([[1,1],[2,2]])

In [9]:
x.sum(axis=0)

array([3, 3])

In [10]:
x.sum(axis=1)

array([2, 4])

In [11]:
x=np.array([1,3,2])

In [12]:
x.min()

1

In [13]:
x.max()

3

In [14]:
x.argmin()   #index of minimum element

0

In [15]:
x.argmax()  #index of maximum element

1

In [16]:
np.all([True,True,False])  #like and operator

False

In [17]:
np.any([True,False,False])   #like or operator

True

In [18]:
a=np.zeros((50,50))

In [19]:
np.any(a!=0)

False

In [20]:
np.all(a==a)

True

In [21]:
a=np.array([1,2,3,2])

In [22]:
b=np.array([2,2,3,2])

In [23]:
c=np.array([6,4,4,3])

In [24]:
((a<=b) & (b<=c)).all()

True

In [25]:
x=np.array([1,2,3,1])

In [26]:
y=np.array([1,2,3],[5,6,1])

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [27]:
y=np.array([[1,2,3],[5,6,1]])

In [28]:
x.mean()

1.75

In [29]:
np.median(x)

1.5

In [30]:
np.median(y,axis=1)

array([2., 5.])

In [31]:
x.std() #Full population standard dev.

0.82915619758885