In [2]:
import numpy as np
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

# All arithmetc operations element wise

In [5]:
a=[1,2,3,4]
b=np.ones(4)+1
b

array([2., 2., 2., 2.])

In [6]:
a-b

array([-1.,  0.,  1.,  2.])

# Matrix Multiplication

In [8]:
c=np.diag([1,2,3,4])
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [9]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# comparisons

In [10]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b

array([False,  True, False,  True])

In [11]:
a>b

array([False, False,  True, False])

# Arraywise comparisons

In [12]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])
np.array_equal(a,b)

False

In [13]:
np.array_equal(b,c)

False

In [14]:
np.array_equal(a,c)

True

# Logical Operations

In [15]:
a=np.array([1,1,0,0],dtype=bool)

In [16]:
b=np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [17]:
np.logical_and(a,b)

array([ True, False, False, False])

# Transcendental functions

In [18]:
a=np.arange(5)

In [19]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [20]:
np.log(a)

C:\Users\DIPANKAR\AppData\Local\Temp/ipykernel_11244/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [21]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# Shapes mismatch

In [22]:
a=np.arange(4)

In [23]:
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

In [24]:
x=np.array([1,2,3,4])
np.sum(a)

6

In [27]:
x=np.array(([1,1],[2,2]))

In [28]:
x

array([[1, 1],
       [2, 2]])

In [29]:
x.sum(axis=0)

array([3, 3])

In [30]:
x.sum(axis=1)

array([2, 4])

# Other Reductions

In [31]:
x=np.array([1,3,2])
x.min()

1

In [32]:
x.max()

3

In [33]:
x.argmin()

0

In [34]:
x.argmax()

1

# Logical Opeartions

In [35]:
np.all([True,False,True])#like and

False

In [36]:
np.any([True,False,True]) #like or

True

In [38]:
a=np.zeros((50,50))

In [39]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
np.any(a!=0)

False

In [41]:
np.all(a==a)

True

In [43]:
a=np.array([1,2,3,2])  #(a<=b)->[T T T T] &
b=np.array([2,2,3,3])  #(b<=c)->[T T T T]
c=np.array([6,4,4,5])
((a<=b) &(b<=c)).all()# [T T T T ].all()

True

# statstics

In [44]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [46]:
np.median(x)

1.5

In [47]:
np.median(y,axis=1)

array([2., 5.])

In [48]:
x.std()

0.82915619758885

# Load data into numpy array object

In [50]:
data=np.loadtxt('populations.txt')

In [51]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [52]:
year,hear,lynxes,carrots=data.T

In [53]:
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


# The mean population overtime

In [54]:
populations=data[:,1:]

In [55]:
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

# Standard Deviation

In [56]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

# Which species has the highest populations each year

In [57]:
np.argmax(populations,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

# Broadcasting

In [58]:
a=np.tile(np.arange(0,40,10),(3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [59]:
a=a.T
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [60]:
a=np.tile(np.arange(0,40,10),(3,2))

In [63]:
b=np.array([0,1,2])

In [64]:
b

array([0, 1, 2])

In [65]:
a+b

ValueError: operands could not be broadcast together with shapes (3,8) (3,) 

In [66]:
a=np.arange(0,40,10)

In [67]:
a

array([ 0, 10, 20, 30])

In [68]:
a.shape

(4,)

In [69]:
a=a[:,np.newaxis]

In [70]:
a.shape

(4, 1)

In [71]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [72]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Array shape Manipulation

In [73]:
# 2D->1D

In [76]:
a=np.array(([1,2,3],[4,5,6]))
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [79]:
a=a.T

In [80]:
a.ravel()

array([1, 4, 2, 5, 3, 6])

# Reshaping

In [81]:
print(a.shape)

(3, 2)


In [82]:
a

array([[1, 4],
       [2, 5],
       [3, 6]])

In [83]:
b=a.ravel()

In [84]:
b

array([1, 4, 2, 5, 3, 6])

In [87]:
b=b.reshape((2,3)) # change to 2x3 matrix

In [88]:
b

array([[1, 4, 2],
       [5, 3, 6]])

In [89]:
b[0,0]=100

In [90]:
b

array([[100,   4,   2],
       [  5,   3,   6]])

# Note & Beware-> Reshape may also return a copy

In [92]:
a=np.zeros((3,2))

In [93]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [94]:
b=a.T.reshape(3,2)

In [95]:
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [96]:
b[0]=50

In [97]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# Adding a Dimention

In [98]:
z=np.array([1,2,3])

In [99]:
z

array([1, 2, 3])

In [100]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

# Dimention shuffling

In [103]:
a=np.arange(4*3*2).reshape(4,3,2)

In [104]:
a.shape

(4, 3, 2)

In [105]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [106]:
a[0,2,1]

5

In [107]:
a=np.arange(4)

In [108]:
a.resize((8,))

In [109]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [110]:
b=a

In [111]:
a.resize((4,9))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

# sorting data

In [112]:
a=np.array(([5,4,6],[2,3,2]))

In [113]:
b=np.sort(a,axis=1)

In [114]:
b

array([[4, 5, 6],
       [2, 2, 3]])

# inplace sort

In [115]:
a.sort(axis=1)

In [116]:
a

array([[4, 5, 6],
       [2, 2, 3]])

# sorting with fancy indexing

In [119]:
a=np.array([4,3,1,2])
j=np.argsort(a)  #indexes are print
j

array([2, 3, 1, 0], dtype=int64)

In [120]:
a[j]

array([1, 2, 3, 4])