# Introduction

In [2]:
import numpy as np

In [2]:
a=np.array([0,1,2,3])

In [3]:
print(a)

[0 1 2 3]


In [4]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [5]:
L=range(1000)
%timeit [i**2 for i in L]

525 µs ± 188 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a=np.arange(1000)
%timeit a**2

3.02 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Creating Arrays

In [7]:
a=np.array([0,1,2,3])

In [8]:
a


array([0, 1, 2, 3])

In [9]:
a.ndim

1

In [10]:
a.shape

(4,)

In [11]:
len(a)

4

In [12]:
b=np.array([[0,1,2],[3,4,5]])

In [13]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [16]:
len(b)

2

In [18]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 2)

# Functions for creating Arrays

In [21]:
a=np.arange(10)

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b=np.arange(1,10,2)

In [24]:
b

array([1, 3, 5, 7, 9])

# Using Linespace

In [25]:
a=np.linspace(0,1,6)

In [26]:
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

# Common Array

In [27]:
a=np.ones((3,3))

In [28]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
b=np.zeros((3,3))

In [30]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Identity Matrix

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

# Create Array using diag function

In [33]:
a=np.diag([1,2,3,4])

In [34]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Extract diagonal

In [35]:
np.diag(a)

array([1, 2, 3, 4])

# Create Array using Random

In [36]:
a=np.random.rand(4)

In [37]:
a

array([0.60643941, 0.78188755, 0.05128677, 0.57768682])

In [38]:
a=np.random.rand(4)

In [39]:
a

array([0.21616102, 0.01920074, 0.94397842, 0.63205703])

# Basic Data Types

In [40]:
a=np.arange(10)

In [41]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.dtype

dtype('int32')

# you can explicitly specify which data type you want

In [46]:
a=np.arange(10,dtype='float32')

In [47]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

# The default dat type is float for zeros and Ones function

In [48]:
a=np.zeros((3,3))

In [49]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
a.dtype

dtype('float64')

# Other data type

In [51]:
d=np.array([1+2j,2+4j])

In [52]:
d.dtype

dtype('complex128')

In [53]:
s=np.array(['Ram','Robert','Rahim'])
s.dtype

dtype('<U6')

# Indexing and Slicing

In [3]:

a=np.arange(10)

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [6]:
print(a[2,2])

3


In [7]:
a[2,2]=5

In [8]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 5]])

# slicing

In [9]:
a=np.arange(10)

In [10]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a[1:8:2]

array([1, 3, 5, 7])

In [12]:
a=np.arange(10)

In [13]:
a[5:]=10

In [14]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [15]:
b=np.arange(5)

In [16]:
a[5:]=b[::-1]

In [17]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# Copies and views

In [18]:
a=np.arange(10)

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b=a[::2]

In [21]:
b

array([0, 2, 4, 6, 8])

In [22]:
np.shares_memory(a,b)

True

In [23]:
b[0]=10

In [24]:
b

array([10,  2,  4,  6,  8])

In [25]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [26]:
a=np.arange(10)

In [27]:
c=a[::2].copy()

In [28]:
c

array([0, 2, 4, 6, 8])

In [29]:
np.shares_memory(a,c)

False

In [30]:
c[0]=10

In [31]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Fancy Indexing

In [32]:
a=np.random.randint(0,20,15)

In [33]:
a

array([14, 19, 11, 12,  1, 13,  3, 11, 13,  7,  6, 10,  5, 18,  4])

In [34]:
mask=(a%2==0)

In [35]:
extract_from_a=a[mask]

In [36]:
extract_from_a

array([14, 12,  6, 10, 18,  4])

In [37]:
a[mask]=-1

In [38]:
a

array([-1, 19, 11, -1,  1, 13,  3, 11, 13,  7, -1, -1,  5, -1, -1])

# Indexing with array of integers

In [39]:
a=np.arange(0,100,10)

In [40]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [42]:
a[[9,7]]=-200

In [43]:
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])